### ISSUE TITLE
Add docs and examples for PostgreSQL importer/exporter

### ISSUE THREAD

**Issue by Gerrrr** [Gerrrr/hunter#8]
The scope of this issue is to extend README, add a sample config, and maybe SQL schema:

Configuration:

```yaml
# External systems connectors configuration:
postgres:
  hostname: ${POSTGRES_HOSTNAME}
  port: 5432
  username: ${POSTGRES_USERNAME}
  password: ${POSTGRES_PASSWORD}
  database: ${POSTGRES_DATABASE}

# Templates define common bits shared between test definitions:
templates:
  common:
    type: postgres
    time_column: commit_ts
    attributes: [experiment_id, config_id, commit, samples]
    update_statement: |
      UPDATE results 
        SET {metric}_rel_forward_change=%s, 
            {metric}_rel_backward_change=%s, 
            {metric}_p_value=%s
      WHERE experiment_id = '{experiment_id}' AND config_id = {config_id}
    metrics:
      process_cumulative_rate_mean:
        direction: 1
        scale: 1
      process_cumulative_rate_stderr:
        direction: -1
        scale: 1
      process_cumulative_rate_diff:
        direction: -1
        scale: 1

# Define your tests here:
tests:
  aggregate_mem:
    inherit: [ common ]
    query: |
      SELECT e.commit, 
             e.commit_ts, 
             r.process_cumulative_rate_mean, 
             r.process_cumulative_rate_stderr, 
             r.process_cumulative_rate_diff, 
             r.samples, 
             r.experiment_id, 
             r.config_id
      FROM results r
      INNER JOIN configs c ON r.config_id = c.id
      INNER JOIN experiments e ON r.experiment_id = e.id
      WHERE e.exclude_from_analysis = false AND
            e.branch = '${BRANCH}' AND
            c.store = 'MEM' AND
            c.cache = true AND
            c.log = true AND
            c.keyspace = 10000 AND
            c.key_distribution = 'normal' AND
            c.partitions = 2 AND
            c.instance_type = 'ec2i3.large'
      ORDER BY e.commit_ts ASC;
```

Usage:

```
export POSTGRES_HOSTNAME=...
export POSTGRES_USERNAME=...
export POSTGRES_PASSWORD=...
export POSTGRES_DATABASE=...
$ BRANCH=trunk HUNTER_CONFIG=resources/hunter.yaml hunter analyze stateheavy_time_rocks
```
